
name: App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: npm install
    
    - name: Build
      run: npm run build
      
    # Upload build artifacts for deployment
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-files
        path: dist/
      
  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Download the build artifacts
    - name: Download Build Artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-files
        path: dist
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/web-app:latest
        
    # Add a concrete deployment step for your specific platform
    - name: Deploy to Server
      if: success()
      run: |
        echo "Deploying to production server"
        # You can add SSH deployment, AWS, Azure, etc., based on your hosting
        # Example for SSH deployment:
        # Install SSH key
        # mkdir -p ~/.ssh
        # echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        # chmod 600 ~/.ssh/id_rsa
        # echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
        # Deploy using SSH
        # ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "docker pull ${{ secrets.DOCKER_USERNAME }}/web-app:latest && docker-compose -f /path/to/docker-compose.yml up -d"
